/* eslint-disable */
// tslint:disable
/**
 * Patients Appointment
 * Patient Appointment
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import * as appointment from './api/appointment/types'

export interface ApiImplementation {
	appointment: appointment.AppointmentApi
}
